### ISSUE TITLE
Openssl and cmake

### ISSUE THREAD

**Issue by crazyhappygame** [cocos2d/cocos2d-x-external#27]
@rcdailey could you recommend us how to build openssl with cmake?
I have seen your issue:
https://github.com/openssl/openssl/issues/4345

**Comment by rcdailey** [comment]
CMake support in OpenSSL just quite simply doesn't exist. Furthermore, the developers are completely uninterested in it. They have to be willing to transition their build system over, for a couple of obvious reasons:

1. They have to maintain it and use it on a day to day basis after the initial scripts are written.
1. They won't want to maintain 2 separate build systems (one for those that prefer CMake, and the original one for those that were happy with that).

I still prefer CMake for all projects because of the unity it brings to build systems and platforms, but there's no sense in continuing the conversation there if they can't be convinced. And that's fine, it's their project.

I guess the point of me saying all of this is: There's no recommendation I can give that you would reasonably expect. Truly you would have to write CMake scripts for OpenSSL from the ground up. In the thread you linked, I did mention some other repository that has started on this, but those are not maintained and they are ad-hoc builds, so may not work on all configurations and platforms.

I don't have a good answer for you, sorry!

**Comment by crazyhappygame** [comment]
@rcdailey What do you think it will be easiest f(platforms win, linux, mac. ios, android):
1. create and support CMakeLists.txt
2. use ExternalProject_Add and call perl script Configure

**Comment by crazyhappygame** [comment]
I think that we should use www.libressl.org instead of openssl
Advantages:
1. Support cmake
2. No files generation during build

Another option is boringssl
